### ISSUE TITLE
Certain files are failing to decompile.

### ISSUE THREAD

**Issue by Fenteale** [ionescu007/minlzma#6] opened 2020-11-08 09:51 UTC
I have a series of lzma compressed files hosted on an http server that I plan on downloading and decompressing with minlzma.  The issue is, some files fail to decompress for unknown reasons.  I know they are valid files because the linux command `xz` and functions from liblzma can decompress then just fine, but they are failing to decompress with minlzma.

I did do some research into some of the files and it seems like when the "reset state" is 1, it is unhandled, which causes the file decompression to fail.  I tried to implement my own fix for this, however I know very little about the lzma compression method, and may have done it incorrectly.  My attempt can be found [here](https://github.com/Fenteale/minlzma/commit/bc076135ffa5a7ede25ffd1eb2273da4c7975857).  This allowed a lot more files to be decompressed successfully, but there were still some left that I did not look into very deeply that failed.

I have attached a zip file called "reset-state" which contains files that failed for me because of the reset state, and one called "misc-fail" that failed for some other unknown reason.

[reset-state.zip](https://github.com/ionescu007/minlzma/files/5506100/reset-state.zip)
[misc-fail.zip](https://github.com/ionescu007/minlzma/files/5506109/misc-fail.zip)

If you wish to view the entire repository of lzma compressed files, they
 are currently being hosted here:
https://svn.openfortress.fun/files/

And for reference, this is how I tried implementing minlzma in the launcher:
https://github.com/Walaryne/oflauncher-stainless/blob/bc03388f1bd427af906511d3d72de7f2d40278f9/src/launcher/net/OFSNet.cpp#L61

**Comment by ionescu007** [comment] 2020-11-24 18:14
Just wanted to comment here publicly since we talked on Twitter, and I don't want external people to look at the repo and feel I'm ignoring issues :)

1) Confirmed those files are failing due to 3 reasons
    * Lack of support for 'soft' dictionary reset. I had never seen this happening before. Will add support for this.
    * An issue that was found in some other internal testing, that will have a PR up for soon. This fixes the vast majority of the other files.
    * Compressed empty files. I believe you can just make sure openfortress never sends compressed empty files. I don't really want to handle this scenario :)

2) By early next week, these issues should be addressed in the repo and your files should work. Would be awesome to see the launcher go back to using minlzma :)

**Closed as completed** 2020-11-30 15:40 UTC
